# Site settings
logo: "/assets/img/logo.png"
title: "Farhana - One Page Business Agency Jekyll Theme"
email: "autworks2018@gmail.com"
description: "Farhana Jekyll is an one page Jekyll theme to create creative agency website or business support portal. You will get a clean, polished and modern website with Farhana Jekyll Theme. Itâ€™s a ready website template for your creative agency portal solution."
keywords: "jekyll, minimal jekyll, jekyll theme, responsive jekyll, seo friendly blog, super fast blog, responsive"
baseurl: "theme-farhana" # the subpath of your site, e.g. /blog
url: "https://abuubaidah.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: farhana-3
